const countries = [
    { id: 1, country: "Afghanistan" },
    { id: 2, country: "Albania" },
    { id: 3, country: "Algeria" },
    { id: 4, country: "Andorra" },
    { id: 5, country: "Angola" },
    { id: 6, country: "Antigua and Barbuda" },
    { id: 7, country: "Argentina" },
    { id: 8, country: "Armenia" },
    { id: 9, country: "Australia" },
    { id: 10, country: "Austria" },
    { id: 11, country: "Azerbaijan" },
    { id: 12, country: "Bahamas" },
    { id: 13, country: "Bahrain" },
    { id: 14, country: "Bangladesh" },
    { id: 15, country: "Barbados" },
    { id: 16, country: "Belarus" },
    { id: 17, country: "Belgium" },
    { id: 18, country: "Belize" },
    { id: 19, country: "Benin" },
    { id: 20, country: "Bhutan" },
    { id: 21, country: "Bolivia" },
    { id: 22, country: "Bosnia and Herzegovina" },
    { id: 23, country: "Botswana" },
    { id: 24, country: "Brazil" },
    { id: 25, country: "Brunei" },
    { id: 26, country: "Bulgaria" },
    { id: 27, country: "Burkina Faso" },
    { id: 28, country: "Burundi" },
    { id: 29, country: "Cabo Verde" },
    { id: 30, country: "Cambodia" },
    { id: 31, country: "Cameroon" },
    { id: 32, country: "Canada" },
    { id: 33, country: "Central African Republic" },
    { id: 34, country: "Chad" },
    { id: 35, country: "Chile" },
    { id: 36, country: "China" },
    { id: 37, country: "Colombia" },
    { id: 38, country: "Comoros" },
    { id: 39, country: "Congo" },
    { id: 40, country: "Costa Rica" },
    { id: 41, country: "Croatia" },
    { id: 42, country: "Cuba" },
    { id: 43, country: "Cyprus" },
    { id: 44, country: "Czech Republic" },
    { id: 45, country: "Denmark" },
    { id: 46, country: "Djibouti" },
    { id: 47, country: "Dominica" },
    { id: 48, country: "Dominican Republic" },
    { id: 49, country: "Ecuador" },
    { id: 50, country: "Egypt" },
    { id: 51, country: "El Salvador" },
    { id: 52, country: "Equatorial Guinea" },
    { id: 53, country: "Eritrea" },
    { id: 54, country: "Estonia" },
    { id: 55, country: "Eswatini" },
    { id: 56, country: "Ethiopia" },
    { id: 57, country: "Fiji" },
    { id: 58, country: "Finland" },
    { id: 59, country: "France" },
    { id: 60, country: "Gabon" },
    { id: 61, country: "Gambia" },
    { id: 62, country: "Georgia" },
    { id: 63, country: "Germany" },
    { id: 64, country: "Ghana" },
    { id: 65, country: "Greece" },
    { id: 66, country: "Grenada" },
    { id: 67, country: "Guatemala" },
    { id: 68, country: "Guinea" },
    { id: 69, country: "Guinea-Bissau" },
    { id: 70, country: "Guyana" },
    { id: 71, country: "Haiti" },
    { id: 72, country: "Honduras" },
    { id: 73, country: "Hungary" },
    { id: 74, country: "Iceland" },
    { id: 75, country: "India" },
    { id: 76, country: "Indonesia" },
    { id: 77, country: "Iran" },
    { id: 78, country: "Iraq" },
    { id: 79, country: "Ireland" },
    { id: 80, country: "Israel" },
    { id: 81, country: "Italy" },
    { id: 82, country: "Jamaica" },
    { id: 83, country: "Japan" },
    { id: 84, country: "Jordan" },
    { id: 85, country: "Kazakhstan" },
    { id: 86, country: "Kenya" },
    { id: 87, country: "Kiribati" },
    { id: 88, country: "Korea, North" },
    { id: 89, country: "Korea, South" },
    { id: 90, country: "Kuwait" },
    { id: 91, country: "Kyrgyzstan" },
    { id: 92, country: "Laos" },
    { id: 93, country: "Latvia" },
    { id: 94, country: "Lebanon" },
    { id: 95, country: "Lesotho" },
    { id: 96, country: "Liberia" },
    { id: 97, country: "Libya" },
    { id: 98, country: "Liechtenstein" },
    { id: 99, country: "Lithuania" },
    { id: 100, country: "Luxembourg" },
    { id: 101, country: "Madagascar" },
    { id: 102, country: "Malawi" },
    { id: 103, country: "Malaysia" },
    { id: 104, country: "Maldives" },
    { id: 105, country: "Mali" },
    { id: 106, country: "Malta" },
    { id: 107, country: "Marshall Islands" },
    { id: 108, country: "Mauritania" },
    { id: 109, country: "Mauritius" },
    { id: 110, country: "Mexico" },
    { id: 111, country: "Micronesia" },
    { id: 112, country: "Moldova" },
    { id: 113, country: "Monaco" },
    { id: 114, country: "Mongolia" },
    { id: 115, country: "Montenegro" },
    { id: 116, country: "Morocco" },
    { id: 117, country: "Mozambique" },
    { id: 118, country: "Myanmar" },
    { id: 119, country: "Namibia" },
    { id: 120, country: "Nauru" },
    { id: 121, country: "Nepal" },
    { id: 122, country: "Netherlands" },
    { id: 123, country: "New Zealand" },
    { id: 124, country: "Nicaragua" },
    { id: 125, country: "Niger" },
    { id: 126, country: "Nigeria" },
    { id: 127, country: "North Macedonia" },
    { id: 128, country: "Norway" },
    { id: 129, country: "Oman" },
    { id: 130, country: "Pakistan" },
    { id: 131, country: "Palau" },
    { id: 132, country: "Panama" },
    { id: 133, country: "Papua New Guinea" },
    { id: 134, country: "Paraguay" },
    { id: 135, country: "Peru" },
    { id: 136, country: "Philippines" },
    { id: 137, country: "Poland" },
    { id: 138, country: "Portugal" },
    { id: 139, country: "Qatar" },
    { id: 140, country: "Romania" },
    { id: 141, country: "Russia" },
    { id: 142, country: "Rwanda" },
    { id: 143, country: "Saint Kitts and Nevis" },
    { id: 144, country: "Saint Lucia" },
    { id: 145, country: "Saint Vincent and the Grenadines" },
    { id: 146, country: "Samoa" },
    { id: 147, country: "San Marino" },
    { id: 148, country: "Sao Tome and Principe" },
    { id: 149, country: "Saudi Arabia" },
    { id: 150, country: "Senegal" }
];


const state = [
    { id: 1, country: "Afghanistan", state: "Badakhshan" },
    { id: 2, country: "Afghanistan", state: "Badghis" },
    { id: 3, country: "Afghanistan", state: "Baghlan" },
    { id: 4, country: "Afghanistan", state: "Balkh" },
    { id: 5, country: "Afghanistan", state: "Bamyan" },
    { id: 6, country: "Afghanistan", state: "Daykundi" },
    { id: 7, country: "Afghanistan", state: "Farah" },
    { id: 8, country: "Afghanistan", state: "Faryab" },
    { id: 9, country: "Afghanistan", state: "Ghazni" },
    { id: 10, country: "Afghanistan", state: "Ghor" },
    { id: 11, country: "Afghanistan", state: "Helmand" },
    { id: 12, country: "Afghanistan", state: "Herat" },
    { id: 13, country: "Afghanistan", state: "Jowzjan" },
    { id: 14, country: "Afghanistan", state: "Kabul" },
    { id: 15, country: "Afghanistan", state: "Kandahar" },
    { id: 16, country: "Afghanistan", state: "Kapisa" },
    { id: 17, country: "Afghanistan", state: "Khost" },
    { id: 18, country: "Afghanistan", state: "Kunar" },
    { id: 19, country: "Afghanistan", state: "Kunduz" },
    { id: 20, country: "Afghanistan", state: "Laghman" },
    { id: 21, country: "Afghanistan", state: "Logar" },
    { id: 22, country: "Afghanistan", state: "Nangarhar" },
    { id: 23, country: "Afghanistan", state: "Nimruz" },
    { id: 24, country: "Afghanistan", state: "Nuristan" },
    { id: 25, country: "Afghanistan", state: "Paktia" },
    { id: 26, country: "Afghanistan", state: "Paktika" },
    { id: 27, country: "Afghanistan", state: "Panjshir" },
    { id: 28, country: "Afghanistan", state: "Parwan" },
    { id: 29, country: "Afghanistan", state: "Samangan" },
    { id: 30, country: "Afghanistan", state: "Sar-e Pol" },
    { id: 31, country: "Afghanistan", state: "Takhar" },
    { id: 32, country: "Afghanistan", state: "Urozgan" },
    { id: 33, country: "Afghanistan", state: "Wardak" },
    { id: 34, country: "Afghanistan", state: "Zabul" },
    { id: 35, country: "Albania", state: "Berat" },
    { id: 36, country: "Albania", state: "Dibër" },
    { id: 37, country: "Albania", state: "Durrës" },
    { id: 38, country: "Albania", state: "Elbasan" },
    { id: 39, country: "Albania", state: "Fier" },
    { id: 40, country: "Albania", state: "Gjirokastër" },
    { id: 41, country: "Albania", state: "Korçë" },
    { id: 42, country: "Albania", state: "Kukës" },
    { id: 43, country: "Albania", state: "Lezhë" },
    { id: 44, country: "Albania", state: "Shkodër" },
    { id: 45, country: "Albania", state: "Tiranë" },
    { id: 46, country: "Albania", state: "Vlorë" },

    { id: 47, country: "Algeria", state: "Adrar" },
{ id: 48, country: "Algeria", state: "Chlef" },
{ id: 49, country: "Algeria", state: "Laghouat" },
{ id: 50, country: "Algeria", state: "Oum El Bouaghi" },
{ id: 51, country: "Algeria", state: "Batna" },
{ id: 52, country: "Algeria", state: "Béjaïa" },
{ id: 53, country: "Algeria", state: "Biskra" },
{ id: 54, country: "Algeria", state: "Blida" },
{ id: 55, country: "Algeria", state: "Bouira" },
{ id: 56, country: "Algeria", state: "Tamanrasset" },
{ id: 57, country: "Algeria", state: "Tébessa" },
{ id: 58, country: "Algeria", state: "Tlemcen" },
{ id: 59, country: "Algeria", state: "Tiaret" },

{ id: 60, country: "Algeria", state: "Alger" },
{ id: 61, country: "Algeria", state: "Djelfa" },
{ id: 62, country: "Algeria", state: "Tizi Ouzou" },
{ id: 63, country: "Algeria", state: "Algeria" },
{ id: 64, country: "Algeria", state: "Annaba" },
{ id: 65, country: "Algeria", state: "Guelma" },
{ id: 66, country: "Algeria", state: "Constantine" },
{ id: 67, country: "Algeria", state: "Médéa" },
{ id: 68, country: "Algeria", state: "Mostaganem" },
{ id: 69, country: "Algeria", state: "M'sila" },
{ id: 70, country: "Algeria", state: "Mascara" },
{ id: 71, country: "Algeria", state: "Ouargla" },
{ id: 72, country: "Algeria", state: "Oran" },
// start from here
{ id: 73, country: "Algeria", state: "El Bayadh" },
{ id: 74, country: "Algeria", state: "Illizi" },
{ id: 75, country: "Algeria", state: "Bordj Bou Arreridj" },
{ id: 76, country: "Algeria", state: "Boumerdès" },
{ id: 77, country: "Algeria", state: "El Tarf" },
{ id: 78, country: "Algeria", state: "Tindouf" },
{ id: 79, country: "Algeria", state: "Tissemsilt" },
{ id: 80, country: "Algeria", state: "Sidi Bel Abbès" },
{ id: 81, country: "Algeria", state: "Setif" },
{ id: 82, country: "Algeria", state: "Saïda" },
{ id: 83, country: "Algeria", state: "Skikda" },
{ id: 84, country: "Algeria", state: "Tipaza" },
{ id: 85, country: "Algeria", state: "Mila" },
{ id: 86, country: "Algeria", state: "Aïn Defla" },
{ id: 87, country: "Algeria", state: "Naâma" },
{ id: 88, country: "Algeria", state: "Aïn Témouchent" },
{ id: 89, country: "Algeria", state: "Ghardaïa" },
{ id: 90, country: "Algeria", state: "Relizane" },
{ id: 91, country: "Algeria", state: "El Oued" },
{ id: 92, country: "Algeria", state: "Khenchela" },
{ id: 93, country: "Algeria", state: "Souk Ahras" },
{ id: 94, country: "Algeria", state: "Tipaza" },
{ id: 95, country: "Algeria", state: "Tébessa" },
{ id: 96, country: "Algeria", state: "Alger" },
{ id: 97, country: "Algeria", state: "Djelfa" },

]

const cities = [
    { id: 1, city: "Fayzabad", state: "Badakhshan", country: "Afghanistan" },
    { id: 2, city: "Ishkashim", state: "Badakhshan", country: "Afghanistan" },
    { id: 3, city: "Khwahan", state: "Badakhshan", country: "Afghanistan" },
    { id: 4, city: "Khandud", state: "Badakhshan", country: "Afghanistan" },
    { id: 5, city: "Zebak", state: "Badakhshan", country: "Afghanistan" },
    { id: 6, city: "Ziraki", state: "Badakhshan", country: "Afghanistan" },
    { id: 7, city: "Qala-e-Naw", state: "Badghis", country: "Afghanistan" },
    { id: 8, city: "Bala Murghab", state: "Badghis", country: "Afghanistan" },
    { id: 9, city: "Ghormach", state: "Badghis", country: "Afghanistan" },
    { id: 10, city: "Cheshmeh-ye Yanbolaq", state: "Badghis", country: "Afghanistan" },
    { id: 11, city: "Ab Bakhsh", state: "Badghis", country: "Afghanistan" },
    { id: 12, city: "Ab Khuda'i", state: "Badghis", country: "Afghanistan" },
    { id: 13, city: "Abshar", state: "Badghis", country: "Afghanistan" },
    { id: 14, city: "Babula'i", state: "Badghis", country: "Afghanistan" },
    { id: 15, city: "Bahador Khani", state: "Badghis", country: "Afghanistan" },
    { id: 16, city: "Bala Bowkan", state: "Badghis", country: "Afghanistan" },
    { id: 17, city: "Bayah", state: "Badghis", country: "Afghanistan" },
    { id: 18, city: "Baybacheh", state: "Badghis", country: "Afghanistan" },
    { id: 19, city: "Bazartu", state: "Badghis", country: "Afghanistan" },
    { id: 20, city: "Bidak", state: "Badghis", country: "Afghanistan" },
    { id: 21, city: "Bozba'i", state: "Badghis", country: "Afghanistan" },
    { id: 22, city: "Pul-e-Khumri", state: "Baghlan", country: "Afghanistan" },
    { id: 23, city: "Dahana-i-Ghori", state: "Baghlan", country: "Afghanistan" },
    { id: 24, city: "Baghlani Jadid", state: "Baghlan", country: "Afghanistan" },
    { id: 25, city: "Khinjan", state: "Baghlan", country: "Afghanistan" },
    { id: 26, city: "Tala wa Barfak", state: "Baghlan", country: "Afghanistan" },
    { id: 27, city: "Nahrin", state: "Baghlan", country: "Afghanistan" },
    { id: 28, city: "Banu", state: "Baghlan", country: "Afghanistan" },
    { id: 29, city: "Pul-i-Hesar", state: "Baghlan", country: "Afghanistan" },
    { id: 30, city: "Paghman", state: "Baghlan", country: "Afghanistan" },
    { id: 31, city: "Sayed Abad", state: "Baghlan", country: "Afghanistan" },
    { id: 32, city: "Mazar-i-Sharif", state: "Balkh", country: "Afghanistan" },
    { id: 33, city: "Charbolak", state: "Balkh", country: "Afghanistan" },
    { id: 34, city: "Kishindeh", state: "Balkh", country: "Afghanistan" },
    { id: 35, city: "Sholgara", state: "Balkh", country: "Afghanistan" },
    { id: 36, city: "Dawlatabad", state: "Balkh", country: "Afghanistan" },
    { id: 37, city: "Khulm", state: "Balkh", country: "Afghanistan" },
    { id: 38, city: "Chahar Bolak", state: "Balkh", country: "Afghanistan" },
    { id: 39, city: "Zari", state: "Balkh", country: "Afghanistan" },
    { id: 40, city: "Balkh", state: "Balkh", country: "Afghanistan" },
    { id: 41, city: "Nahr-i-Shahi", state: "Balkh", country: "Afghanistan" },
    { id: 41, city: "Bamyan", state: "Bamyan", country: "Afghanistan" },
    { id: 42, city: "Yakawlang", state: "Bamyan", country: "Afghanistan" },
    { id: 43, city: "Panjab", state: "Bamyan", country: "Afghanistan" },
    { id: 44, city: "Shibar", state: "Bamyan", country: "Afghanistan" },
    { id: 45, city: "Jaghori", state: "Bamyan", country: "Afghanistan" },
    { id: 46, city: "Nili", state: "Daykundi", country: "Afghanistan" },
    { id: 47, city: "Khidir", state: "Daykundi", country: "Afghanistan" },
    { id: 48, city: "Gelan", state: "Daykundi", country: "Afghanistan" },
    { id: 49, city: "Daykundi", state: "Daykundi", country: "Afghanistan" },
    { id: 50, city: "Shahrak", state: "Daykundi", country: "Afghanistan" },
    { id: 51, city: "Farah", state: "Farah", country: "Afghanistan" },
    { id: 52, city: "Bala Buluk", state: "Farah", country: "Afghanistan" },
    { id: 53, city: "Khak-i-Safid", state: "Farah", country: "Afghanistan" },
    { id: 54, city: "Pusht Rod", state: "Farah", country: "Afghanistan" },
    { id: 55, city: "Gulistan", state: "Farah", country: "Afghanistan" },
    { id: 56, city: "Maymana", state: "Faryab", country: "Afghanistan" },
    { id: 57, city: "Andkhoy", state: "Faryab", country: "Afghanistan" },
    { id: 58, city: "Qaysar", state: "Faryab", country: "Afghanistan" },
    { id: 59, city: "Almar", state: "Faryab", country: "Afghanistan" },
    { id: 60, city: "Ghowrmach", state: "Faryab", country: "Afghanistan" },
    { id: 61, city: "Ghazni", state: "Ghazni", country: "Afghanistan" },
    { id: 62, city: "Jaghato", state: "Ghazni", country: "Afghanistan" },
    { id: 63, city: "Waghaz", state: "Ghazni", country: "Afghanistan" },
    { id: 64, city: "Khwaja Omari", state: "Ghazni", country: "Afghanistan" },
    { id: 65, city: "Deh Yak", state: "Ghazni", country: "Afghanistan" },
    { id: 66, city: "Chaghcharan", state: "Ghor", country: "Afghanistan" },
    { id: 67, city: "Taywara", state: "Ghor", country: "Afghanistan" },
    { id: 68, city: "Lal wa Sarjangal", state: "Ghor", country: "Afghanistan" },
    { id: 69, city: "Shahrak", state: "Ghor", country: "Afghanistan" },
    { id: 70, city: "Du Layna", state: "Ghor", country: "Afghanistan" },
    { id: 71, city: "Lashkar Gah", state: "Helmand", country: "Afghanistan" },
    { id: 72, city: "Gereshk", state: "Helmand", country: "Afghanistan" },
    { id: 73, city: "Nad Ali", state: "Helmand", country: "Afghanistan" },
    { id: 74, city: "Sangin", state: "Helmand", country: "Afghanistan" },
    { id: 75, city: "Marjah", state: "Helmand", country: "Afghanistan" },
    { id: 76, city: "Herat", state: "Herat", country: "Afghanistan" },
    { id: 77, city: "Shindand", state: "Herat", country: "Afghanistan" },
    { id: 78, city: "Gulran", state: "Herat", country: "Afghanistan" },
    { id: 79, city: "Pashtun Zarghun", state: "Herat", country: "Afghanistan" },
    { id: 80, city: "Farsi", state: "Herat", country: "Afghanistan" },
    { id: 81, city: "Sheberghan", state: "Jowzjan", country: "Afghanistan" },
    { id: 82, city: "Mardyan", state: "Jowzjan", country: "Afghanistan" },
    { id: 83, city: "Qush Tepa", state: "Jowzjan", country: "Afghanistan" },
    { id: 84, city: "Darzab", state: "Jowzjan", country: "Afghanistan" },
    { id: 85, city: "Khamyab", state: "Jowzjan", country: "Afghanistan" },
    { id: 86, city: "Kabul", state: "Kabul", country: "Afghanistan" },
    { id: 87, city: "Bagram", state: "Kabul", country: "Afghanistan" },
    { id: 88, city: "Logar", state: "Kabul", country: "Afghanistan" },
    { id: 89, city: "Paghman", state: "Kabul", country: "Afghanistan" },
    { id: 90, city: "Kabul City", state: "Kabul", country: "Afghanistan" },
    { id: 91, city: "Kandahar", state: "Kandahar", country: "Afghanistan" },
    { id: 92, city: "Spin Boldak", state: "Kandahar", country: "Afghanistan" },
    { id: 93, city: "Zhari", state: "Kandahar", country: "Afghanistan" },
    { id: 94, city: "Dand", state: "Kandahar", country: "Afghanistan" },
    { id: 95, city: "Shah Wali Kot", state: "Kandahar", country: "Afghanistan" },
    { id: 96, city: "Mahmood Raqi", state: "Kapisa", country: "Afghanistan" },
    { id: 97, city: "Hindukush", state: "Kapisa", country: "Afghanistan" },
    { id: 98, city: "Kohistan", state: "Kapisa", country: "Afghanistan" },
    { id: 99, city: "Tagab", state: "Kapisa", country: "Afghanistan" },
    { id: 100, city: "Kalam", state: "Kapisa", country: "Afghanistan" },
    { id: 101, city: "Khost", state: "Khost", country: "Afghanistan" },
    { id: 102, city: "Mandozai", state: "Khost", country: "Afghanistan" },
    { id: 103, city: "Khanikhel", state: "Khost", country: "Afghanistan" },
    { id: 104, city: "Zazai Maidan", state: "Khost", country: "Afghanistan" },
    { id: 105, city: "Sabari", state: "Khost", country: "Afghanistan" },
    { id: 106, city: "Asadabad", state: "Kunar", country: "Afghanistan" },
    { id: 107, city: "Nurgal", state: "Kunar", country: "Afghanistan" },
    { id: 108, city: "Chapa Dara", state: "Kunar", country: "Afghanistan" },
    { id: 109, city: "Marawara", state: "Kunar", country: "Afghanistan" },
    { id: 110, city: "Spera", state: "Kunar", country: "Afghanistan" },
    { id: 111, city: "Kunduz", state: "Kunduz", country: "Afghanistan" },
    { id: 112, city: "Aliabad", state: "Kunduz", country: "Afghanistan" },
    { id: 113, city: "Chardara", state: "Kunduz", country: "Afghanistan" },
    { id: 114, city: "Khanabad", state: "Kunduz", country: "Afghanistan" },
    { id: 115, city: "Imam Sahib", state: "Kunduz", country: "Afghanistan" },
    { id: 116, city: "Mehtar Lam", state: "Laghman", country: "Afghanistan" },
    { id: 117, city: "Alishing", state: "Laghman", country: "Afghanistan" },
    { id: 118, city: "Badpakh", state: "Laghman", country: "Afghanistan" },
    { id: 119, city: "Nari", state: "Laghman", country: "Afghanistan" },
    { id: 120, city: "Laghman City", state: "Laghman", country: "Afghanistan" },
    { id: 121, city: "Pul-e-Alam", state: "Logar", country: "Afghanistan" },
    { id: 122, city: "Baraki Barak", state: "Logar", country: "Afghanistan" },
    { id: 123, city: "Kharwar", state: "Logar", country: "Afghanistan" },
    { id: 124, city: "Mohammad Agha", state: "Logar", country: "Afghanistan" },
    { id: 125, city: "Charkh", state: "Logar", country: "Afghanistan" },
    { id: 126, city: "Jalalabad", state: "Nangarhar", country: "Afghanistan" },
    { id: 127, city: "Behsud", state: "Nangarhar", country: "Afghanistan" },
    { id: 128, city: "Rodat", state: "Nangarhar", country: "Afghanistan" },
    { id: 129, city: "Surkh Rod", state: "Nangarhar", country: "Afghanistan" },
    { id: 130, city: "Shinwari", state: "Nangarhar", country: "Afghanistan" },
    { id: 131, city: "Zaranj", state: "Nimruz", country: "Afghanistan" },
    { id: 132, city: "Chakhansur", state: "Nimruz", country: "Afghanistan" },
    { id: 133, city: "Khash Rod", state: "Nimruz", country: "Afghanistan" },
    { id: 134, city: "Delaram", state: "Nimruz", country: "Afghanistan" },
    { id: 135, city: "Kirkh", state: "Nimruz", country: "Afghanistan" },
    { id: 136, city: "Parun", state: "Nuristan", country: "Afghanistan" },
    { id: 137, city: "Kamdesh", state: "Nuristan", country: "Afghanistan" },
    { id: 138, city: "Wama", state: "Nuristan", country: "Afghanistan" },
    { id: 139, city: "Nurgaram", state: "Nuristan", country: "Afghanistan" },
    { id: 140, city: "Nuristan City", state: "Nuristan", country: "Afghanistan" },
    { id: 141, city: "Gardez", state: "Paktia", country: "Afghanistan" },
    { id: 142, city: "Zurmat", state: "Paktia", country: "Afghanistan" },
    { id: 143, city: "Jani Khel", state: "Paktia", country: "Afghanistan" },
    { id: 144, city: "Paktia", state: "Paktia", country: "Afghanistan" },
    { id: 145, city: "Barmal", state: "Paktia", country: "Afghanistan" },
    { id: 146, city: "Sharan", state: "Paktika", country: "Afghanistan" },
    { id: 147, city: "Gomal", state: "Paktika", country: "Afghanistan" },
    { id: 148, city: "Barmal", state: "Paktika", country: "Afghanistan" },
    { id: 149, city: "Waza Khwa", state: "Paktika", country: "Afghanistan" },
    { id: 150, city: "Yahya Khel", state: "Paktika", country: "Afghanistan" },
    { id: 151, city: "Bazarak", state: "Panjshir", country: "Afghanistan" },
    { id: 152, city: "Anaba", state: "Panjshir", country: "Afghanistan" },
    { id: 153, city: "Panjshir Valley", state: "Panjshir", country: "Afghanistan" },
    { id: 154, city: "Rukh", state: "Panjshir", country: "Afghanistan" },
    { id: 155, city: "Khenj", state: "Panjshir", country: "Afghanistan" },
    { id: 156, city: "Charikar", state: "Parwan", country: "Afghanistan" },
    { id: 157, city: "Bagram", state: "Parwan", country: "Afghanistan" },
    { id: 158, city: "Sayed Khel", state: "Parwan", country: "Afghanistan" },
    { id: 159, city: "Shinwari", state: "Parwan", country: "Afghanistan" },
    { id: 160, city: "Jabal Saraj", state: "Parwan", country: "Afghanistan" },
    { id: 161, city: "Aybak", state: "Samangan", country: "Afghanistan" },
{ id: 162, city: "Khur", state: "Samangan", country: "Afghanistan" },
{ id: 163, city: "Dahan-e-Ghori", state: "Samangan", country: "Afghanistan" },
{ id: 164, city: "Feroz Nakhchir", state: "Samangan", country: "Afghanistan" },
{ id: 165, city: "Ruy-e-Doab", state: "Samangan", country: "Afghanistan" },
{ id: 166, city: "Sar-e Pol", state: "Sar-e Pol", country: "Afghanistan" },
{ id: 167, city: "Kushan", state: "Sar-e Pol", country: "Afghanistan" },
{ id: 168, city: "Sancharak", state: "Sar-e Pol", country: "Afghanistan" },
{ id: 169, city: "Kohestan", state: "Sar-e Pol", country: "Afghanistan" },
{ id: 170, city: "Sayad", state: "Sar-e Pol", country: "Afghanistan" },
{ id: 171, city: "Taloqan", state: "Takhar", country: "Afghanistan" },
{ id: 172, city: "Khwaja Bahauddin", state: "Takhar", country: "Afghanistan" },
{ id: 173, city: "Farkhar", state: "Takhar", country: "Afghanistan" },
{ id: 174, city: "Dasht-e-Qala", state: "Takhar", country: "Afghanistan" },
{ id: 175, city: "Rustaq", state: "Takhar", country: "Afghanistan" },
{ id: 176, city: "Tirin Kot", state: "Urozgan", country: "Afghanistan" },
{ id: 177, city: "Chora", state: "Urozgan", country: "Afghanistan" },
{ id: 178, city: "Deh Rawud", state: "Urozgan", country: "Afghanistan" },
{ id: 179, city: "Khas Urozgan", state: "Urozgan", country: "Afghanistan" },
{ id: 180, city: "Urozgan City", state: "Urozgan", country: "Afghanistan" },
{ id: 181, city: "Maidan Shahr", state: "Wardak", country: "Afghanistan" },
{ id: 182, city: "Jaghato", state: "Wardak", country: "Afghanistan" },
{ id: 183, city: "Sayed Abad", state: "Wardak", country: "Afghanistan" },
{ id: 184, city: "Chak", state: "Wardak", country: "Afghanistan" },
{ id: 185, city: "Wardak City", state: "Wardak", country: "Afghanistan" },
{ id: 186, city: "Qalat", state: "Zabul", country: "Afghanistan" },
{ id: 187, city: "Mizana", state: "Zabul", country: "Afghanistan" },
{ id: 188, city: "Shah Joy", state: "Zabul", country: "Afghanistan" },
{ id: 189, city: "Arghandab", state: "Zabul", country: "Afghanistan" },
{ id: 190, city: "Zabul City", state: "Zabul", country: "Afghanistan" },
{ id: 190, city: "Berat", state: "Berat", country: "Albania" },
{ id: 191, city: "Ura Vajzeze", state: "Berat", country: "Albania" },
{ id: 192, city: "Cakran", state: "Berat", country: "Albania" },
{ id: 193, city: "Mifol", state: "Berat", country: "Albania" },
{ id: 194, city: "Rrëza", state: "Berat", country: "Albania" },
{ id: 195, city: "Gajtan", state: "Berat", country: "Albania" },
{ id: 196, city: "Shushicë", state: "Berat", country: "Albania" },
{ id: 197, city: "Fierza", state: "Berat", country: "Albania" },
{ id: 198, city: "Dibër", state: "Dibër", country: "Albania" },
{ id: 199, city: "Peshkopi", state: "Dibër", country: "Albania" },
{ id: 200, city: "Krasta", state: "Dibër", country: "Albania" },
{ id: 201, city: "Lura", state: "Dibër", country: "Albania" },
{ id: 202, city: "Maliq", state: "Dibër", country: "Albania" },
{ id: 203, city: "Leshkosa", state: "Dibër", country: "Albania" },
{ id: 204, city: "Martanesh", state: "Dibër", country: "Albania" },
{ id: 205, city: "Durrës", state: "Durrës", country: "Albania" },
{ id: 206, city: "Plazh", state: "Durrës", country: "Albania" },
{ id: 207, city: "Shkallnur", state: "Durrës", country: "Albania" },
{ id: 208, city: "Gajtan", state: "Durrës", country: "Albania" },
{ id: 209, city: "Spille", state: "Durrës", country: "Albania" },
{ id: 210, city: "Shetaj", state: "Durrës", country: "Albania" },
{ id: 211, city: "Mali i Robit", state: "Durrës", country: "Albania" },
{ id: 212, city: "Shijak", state: "Durrës", country: "Albania" },
{ id: 213, city: "Elbasan", state: "Elbasan", country: "Albania" },
{ id: 214, city: "Rreth i Dajti", state: "Elbasan", country: "Albania" },
{ id: 215, city: "Shalvash", state: "Elbasan", country: "Albania" },
{ id: 216, city: "Cakran", state: "Elbasan", country: "Albania" },
{ id: 217, city: "Përmet", state: "Elbasan", country: "Albania" },
{ id: 218, city: "Fier", state: "Elbasan", country: "Albania" },
{ id: 219, city: "Cakran", state: "Elbasan", country: "Albania" },
{ id: 220, city: "Fier", state: "Fier", country: "Albania" },
{ id: 221, city: "Patos", state: "Fier", country: "Albania" },
{ id: 222, city: "Novoselë", state: "Fier", country: "Albania" },
{ id: 223, city: "Ura Vajzeze", state: "Fier", country: "Albania" },
{ id: 224, city: "Nartë", state: "Fier", country: "Albania" },
{ id: 225, city: "Lushnje", state: "Fier", country: "Albania" },
{ id: 226, city: "Rrëza", state: "Fier", country: "Albania" },
{ id: 227, city: "Gjirokastër", state: "Gjirokastër", country: "Albania" },
{ id: 228, city: "Çameri", state: "Gjirokastër", country: "Albania" },
{ id: 229, city: "Bajkaj", state: "Gjirokastër", country: "Albania" },
{ id: 230, city: "Dërsnik", state: "Gjirokastër", country: "Albania" },
{ id: 231, city: "Hekal", state: "Gjirokastër", country: "Albania" },
{ id: 232, city: "Bashkia", state: "Gjirokastër", country: "Albania" },
{ id: 233, city: "Korçë", state: "Korçë", country: "Albania" },
{ id: 234, city: "Ersekë", state: "Korçë", country: "Albania" },
{ id: 235, city: "Pogradec", state: "Korçë", country: "Albania" },
{ id: 236, city: "Vithkuq", state: "Korçë", country: "Albania" },
{ id: 237, city: "Leskovik", state: "Korçë", country: "Albania" },
{ id: 238, city: "Malisht", state: "Korçë", country: "Albania" },
{ id: 239, city: "Dërsnik", state: "Korçë", country: "Albania" },
{ id: 240, city: "Kukës", state: "Kukës", country: "Albania" },
{ id: 241, city: "Fushë-Arrëz", state: "Kukës", country: "Albania" },
{ id: 242, city: "Shishtavec", state: "Kukës", country: "Albania" },
{ id: 243, city: "Zapod", state: "Kukës", country: "Albania" },
{ id: 244, city: "Bajkaj", state: "Kukës", country: "Albania" },
{ id: 245, city: "Kalimash", state: "Kukës", country: "Albania" },
{ id: 246, city: "Gajtan", state: "Kukës", country: "Albania" },
{ id: 247, city: "Lezhë", state: "Lezhë", country: "Albania" },
{ id: 248, city: "Shëngjin", state: "Lezhë", country: "Albania" },
{ id: 249, city: "Rubik", state: "Lezhë", country: "Albania" },
{ id: 250, city: "Barç", state: "Lezhë", country: "Albania" },
{ id: 251, city: "Rrëza", state: "Lezhë", country: "Albania" },
{ id: 252, city: "Blaz", state: "Lezhë", country: "Albania" },
{ id: 253, city: "Shkodër", state: "Shkodër", country: "Albania" },
{ id: 254, city: "Vau i Dejës", state: "Shkodër", country: "Albania" },
{ id: 255, city: "Përbreg", state: "Shkodër", country: "Albania" },
{ id: 256, city: "Ana e Malit", state: "Shkodër", country: "Albania" },
{ id: 257, city: "Bajkaj", state: "Shkodër", country: "Albania" },
{ id: 258, city: "Mali i Shoshit", state: "Shkodër", country: "Albania" },
{ id: 259, city: "Tiranë", state: "Tiranë", country: "Albania" },
{ id: 260, city: "Dajti", state: "Tiranë", country: "Albania" },
{ id: 261, city: "Vaqarr", state: "Tiranë", country: "Albania" },
{ id: 262, city: "Kashar", state: "Tiranë", country: "Albania" },
{ id: 263, city: "Zall-Bastar", state: "Tiranë", country: "Albania" },
{ id: 264, city: "Kamëz", state: "Tiranë", country: "Albania" },
{ id: 265, city: "Vlorë", state: "Vlorë", country: "Albania" },
{ id: 266, city: "Orikum", state: "Vlorë", country: "Albania" },
{ id: 267, city: "Rrëza", state: "Vlorë", country: "Albania" },
{ id: 268, city: "Shushicë", state: "Vlorë", country: "Albania" },
{ id: 269, city: "Fierza", state: "Vlorë", country: "Albania" },
{ id: 270, city: "Selenicë", state: "Vlorë", country: "Albania" },
{ id: 271, city: "Himarë", state: "Vlorë", country: "Albania" },
{ id: 272, city: "Adrar", state: "Adrar", country: "Algeria" },
{ id: 273, city: "Zaouiat Kounta", state: "Adrar", country: "Algeria" },
{ id: 274, city: "Timimoun", state: "Adrar", country: "Algeria" },
{ id: 275, city: "Reggane", state: "Adrar", country: "Algeria" },
{ id: 276, city: "Aoulef", state: "Adrar", country: "Algeria" },
{ id: 277, city: "Chlef", state: "Chlef", country: "Algeria" },
{ id: 278, city: "Boudouaou", state: "Chlef", country: "Algeria" },
{ id: 279, city: "Oued Fodda", state: "Chlef", country: "Algeria" },
{ id: 280, city: "Ténès", state: "Chlef", country: "Algeria" },
{ id: 281, city: "Laghouat", state: "Laghouat", country: "Algeria" },
{ id: 282, city: "Aflou", state: "Laghouat", country: "Algeria" },
{ id: 283, city: "Khenchela", state: "Laghouat", country: "Algeria" },
{ id: 284, city: "Oum El Bouaghi", state: "Oum El Bouaghi", country: "Algeria" },
{ id: 285, city: "Bir El Ater", state: "Oum El Bouaghi", country: "Algeria" },
{ id: 286, city: "Aïn Beïda", state: "Oum El Bouaghi", country: "Algeria" },
{ id: 287, city: "Batna", state: "Batna", country: "Algeria" },
{ id: 288, city: "Timgad", state: "Batna", country: "Algeria" },
{ id: 289, city: "Maâsara", state: "Batna", country: "Algeria" },
{ id: 290, city: "Béjaïa", state: "Béjaïa", country: "Algeria" },
{ id: 291, city: "Toudja", state: "Béjaïa", country: "Algeria" },
{ id: 292, city: "Akbou", state: "Béjaïa", country: "Algeria" },
{ id: 293, city: "Biskra", state: "Biskra", country: "Algeria" },
{ id: 294, city: "Tolga", state: "Biskra", country: "Algeria" },
{ id: 295, city: "El Kantara", state: "Biskra", country: "Algeria" },
{ id: 296, city: "Blida", state: "Blida", country: "Algeria" },
{ id: 297, city: "Boufarik", state: "Blida", country: "Algeria" },
{ id: 298, city: "Chréa", state: "Blida", country: "Algeria" },
{ id: 299, city: "Bouira", state: "Bouira", country: "Algeria" },
{ id: 300, city: "M'chedallah", state: "Bouira", country: "Algeria" },
{ id: 301, city: "Tamanrasset", state: "Tamanrasset", country: "Algeria" },
{ id: 302, city: "In Salah", state: "Tamanrasset", country: "Algeria" },
{ id: 303, city: "Tébessa", state: "Tébessa", country: "Algeria" },
{ id: 304, city: "El Hamma", state: "Tébessa", country: "Algeria" },
{ id: 305, city: "Tlemcen", state: "Tlemcen", country: "Algeria" },
{ id: 306, city: "El Aricha", state: "Tlemcen", country: "Algeria" },
{ id: 307, city: "Maghnia", state: "Tlemcen", country: "Algeria" },
{ id: 308, city: "Tiaret", state: "Tiaret", country: "Algeria" },
{ id: 309, city: "Frenda", state: "Tiaret", country: "Algeria" },
{ id: 310, city: "Merine", state: "Tiaret", country: "Algeria" },
{ id: 311, city: "Alger", state: "Alger", country: "Algeria" },
{ id: 312, city: "El Harrach", state: "Alger", country: "Algeria" },
{ id: 313, city: "Bab El Oued", state: "Alger", country: "Algeria" },
{ id: 314, city: "Birkhadem", state: "Alger", country: "Algeria" },
{ id: 315, city: "Kouba", state: "Alger", country: "Algeria" },
{ id: 316, city: "Bordj El Kiffan", state: "Alger", country: "Algeria" },
{ id: 317, city: "Djelfa", state: "Djelfa", country: "Algeria" },
{ id: 318, city: "Messaoud", state: "Djelfa", country: "Algeria" },
{ id: 319, city: "Hassi Bahbah", state: "Djelfa", country: "Algeria" },
{ id: 320, city: "Tizi Ouzou", state: "Tizi Ouzou", country: "Algeria" },
{ id: 321, city: "Azazga", state: "Tizi Ouzou", country: "Algeria" },
{ id: 322, city: "Bouira", state: "Tizi Ouzou", country: "Algeria" },
{ id: 323, city: "Annaba", state: "Annaba", country: "Algeria" },
{ id: 324, city: "El Tarf", state: "Annaba", country: "Algeria" },
{ id: 325, city: "El Kala", state: "Annaba", country: "Algeria" },
{ id: 326, city: "Guelma", state: "Guelma", country: "Algeria" },
{ id: 327, city: "Aïn Makhlouf", state: "Guelma", country: "Algeria" },
{ id: 328, city: "Oued Zenati", state: "Guelma", country: "Algeria" },
{ id: 329, city: "Constantine", state: "Constantine", country: "Algeria" },
{ id: 330, city: "Hamma Bouziane", state: "Constantine", country: "Algeria" },
{ id: 331, city: "Aïn Abid", state: "Constantine", country: "Algeria" },
{ id: 332, city: "Médéa", state: "Médéa", country: "Algeria" },
{ id: 333, city: "Berrouaghia", state: "Médéa", country: "Algeria" },
{ id: 334, city: "El Affroun", state: "Médéa", country: "Algeria" },
{ id: 335, city: "Mostaganem", state: "Mostaganem", country: "Algeria" },
{ id: 336, city: "Aïn Nouissy", state: "Mostaganem", country: "Algeria" },
{ id: 337, city: "Sidi Ali", state: "Mostaganem", country: "Algeria" },
{ id: 338, city: "M'sila", state: "M'sila", country: "Algeria" },
{ id: 339, city: "Ouled Derradj", state: "M'sila", country: "Algeria" },
{ id: 340, city: "Bou Saâda", state: "M'sila", country: "Algeria" },
{ id: 341, city: "Mascara", state: "Mascara", country: "Algeria" },
{ id: 342, city: "Tiaret", state: "Mascara", country: "Algeria" },
{ id: 343, city: "El Bordj", state: "Mascara", country: "Algeria" },
{ id: 344, city: "Ouargla", state: "Ouargla", country: "Algeria" },
{ id: 345, city: "Touggourt", state: "Ouargla", country: "Algeria" },
{ id: 346, city: "Megarine", state: "Ouargla", country: "Algeria" },
{ id: 347, city: "Oran", state: "Oran", country: "Algeria" },
{ id: 348, city: "Bir El Djir", state: "Oran", country: "Algeria" },
{ id: 349, city: "Aïn El Turk", state: "Oran", country: "Algeria" }



];


export { countries, state, cities };