export const product = [
    {
        id: "1",
        Title: "Inception",
        Year: "2010",
        Genre: "Action",
        Director: "Christopher Nolan",
        Actors: "Leonardo DiCaprio, Joseph Gordon-Levitt",
        Plot: "A thief uses dream-sharing tech to plant ideas",
        Poster: "https://m.media-amazon.com/images/S/pv-target-images/cc72ff2193c0f7a85322aee988d6fe1ae2cd9f8800b6ff6e8462790fe2aacaf3.jpg",
        imdbRating: "8.8"
    },
    {
        id: "2",
        Title: "Interstellar",
        Year: "2014",
        Genre: "Sci-Fi",
        Director: "Christopher Nolan",
        Actors: "Matthew McConaughey, Anne Hathaway",
        Plot: "A team travels through a wormhole in space",
        Poster: "https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjI2My00ODA1LTlkNzItOWFjMDU5ZDJlYWY3XkEyXkFqcGc@._V1_.jpg",
        imdbRating: "8.6"
    },
    {
        id: "3",
        Title: "The Dark Knight",
        Year: "2008",
        Genre: "Action",
        Director: "Christopher Nolan",
        Actors: "Christian Bale, Heath Ledger",
        Plot: "Batman faces the Joker's chaos in Gotham",
        Poster: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTfE_qrYMBZ_JB8om-34WGaZARhpX26yWRttqIDvn4_7l--UzX8mxKcPrc59IcvTpEA_G8gPA",
        imdbRating: "9.0"
    },
    {
        id: "4",
        Title: "Titanic",
        Year: "1997",
        Genre: "Romance",
        Director: "James Cameron",
        Actors: "Leonardo DiCaprio, Kate Winslet",
        Plot: "A love story unfolds on the ill-fated Titanic",
        Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlcQXin_CNozAFkv_SSihe5eZ_lvDD5nBqCmQT3xPf6KLlqHloIo5cBRGqwuy8pjuIiZrqoA",
        imdbRating: "7.9"
    },
    {
        id: "5",
        Title: "Avatar",
        Year: "2009",
        Genre: "Sci-Fi",
        Director: "James Cameron",
        Actors: "Sam Worthington, Zoe Saldana",
        Plot: "A marine on Pandora gets involved with natives",
        Poster: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTwJPOxfRiaHwXkICnf6LKMHIPWJPGLx8wht-wZH-qFs0OXXUCBvOeCQTs79z7Bx9odsdsB",
        imdbRating: "7.8"
    },
    {
        id: "6",
        Title: "The Matrix",
        Year: "1999",
        Genre: "Sci-Fi",
        Director: "Lana Wachowski",
        Actors: "Keanu Reeves, Laurence Fishburne",
        Plot: "A hacker discovers the truth about his reality",
        Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCWXVvfvZR3oe7PCMM0exwV0dObOTKvLfSM-bjvKpQ1VegKXuCtq6aBrxqbIgUNxMbfavy",
        imdbRating: "8.7"
    },
    {
        id: "7",
        Title: "Gladiator",
        Year: "2000",
        Genre: "Action",
        Director: "Ridley Scott",
        Actors: "Russell Crowe, Joaquin Phoenix",
        Plot: "A Roman general seeks revenge for his family",
        Poster: "https://m.media-amazon.com/images/M/MV5BYWQ4YmNjYjEtOWE1Zi00Y2U4LWI4NTAtMTU0MjkxNWQ1ZmJiXkEyXkFqcGc@._V1_.jpg",
        imdbRating: "8.5"
    },
    {
        id: "8",
        Title: "Joker",
        Year: "2019",
        Genre: "Drama",
        Director: "Todd Phillips",
        Actors: "Joaquin Phoenix, Robert De Niro",
        Plot: "A troubled man becomes Gotham's clown villain",
        Poster: "https://upload.wikimedia.org/wikipedia/en/e/e1/Joker_%282019_film%29_poster.jpg",
        imdbRating: "8.4"
    },
    {
        id: "9",
        Title: "Avengers: Endgame",
        Year: "2019",
        Genre: "Action",
        Director: "Anthony Russo",
        Actors: "Robert Downey Jr., Chris Evans",
        Plot: "Heroes unite to defeat Thanos and restore order",
        Poster: "https://preview.redd.it/esea05pj84o21.jpg?width=640&crop=smart&auto=webp&s=d00beefa8e27448e4ddd422eb3500ae069adf0f1",
        imdbRating: "8.4"
    },
    {
        id: "10",
        Title: "Iron Man",
        Year: "2008",
        Genre: "Action",
        Director: "Jon Favreau",
        Actors: "Robert Downey Jr., Gwyneth Paltrow",
        Plot: "A billionaire builds a suit to fight evil",
        Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCythtaM-iOKWi0JUUiQtcC3CH8o9bhUDiaFY53ZRWXFa4mGuVRFevtTZlWDusVoP6dl3e",
        imdbRating: "7.9"
    },
    {
        id: "11",
        Title: "Black Panther",
        Year: "2018",
        Genre: "Action",
        Director: "Ryan Coogler",
        Actors: "Chadwick Boseman, Michael B. Jordan",
        Plot: "The king of Wakanda fights to save his kingdom",
        Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1MSjVz4AlBMvl3RD0eXqenCdZbowXC-2uGUcgYGSrtuOdsVAGWVYmJ24_wB54zLkMxaVU",
        imdbRating: "7.3"
    },
    {
        id: "12",
        Title: "Spider-Man: No Way Home",
        Year: "2021",
        Genre: "Action",
        Director: "Jon Watts",
        Actors: "Tom Holland, Zendaya",
        Plot: "Spider-Man faces villains from other universes",
        Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJXG-39ax_uSWVuU05XI2eynuf0D9rcrNmFBJfCDIm_K9A2SUdFTMRREZ7JVqliTX3NodG9A",
        imdbRating: "8.2"
    },
    {
        id: "13",
        Title: "Doctor Strange",
        Year: "2016",
        Genre: "Fantasy",
        Director: "Scott Derrickson",
        Actors: "Benedict Cumberbatch, Rachel McAdams",
        Plot: "A surgeon learns magic to protect the world",
        Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWCvm2jN-QykoEwZJivikl3aQeUw2gxcI5WvWU5Kmx2tmIwMBdu9Bjpkw_9ztcNyumv03T1A",
        imdbRating: "7.5"
    },
    {
        id: "14",
        Title: "The Lion King",
        Year: "1994",
        Genre: "Animation",
        Director: "Roger Allers",
        Actors: "Matthew Broderick, Jeremy Irons",
        Plot: "A lion cub finds his destiny as king",
        Poster: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTv0REMOInqkdMG-8AbTQIVTv9bmlN6O6CM0yh12hG_uQ_U66Q2k0aQVj2ajafAYWOrWUJt3A",
        imdbRating: "8.5"
    },
    {
        id: "15",
        Title: "Frozen",
        Year: "2013",
        Genre: "Animation",
        Director: "Chris Buck",
        Actors: "Kristen Bell, Idina Menzel",
        Plot: "Two sisters deal with icy powers and love",
        Poster: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRSy7tBVMBxnb3qDs2KL2wvdx3lZhWZ2DYjg-yKqpKotvZd_f4cq9WLORbfNKl_3-kJzHJO",
        imdbRating: "7.4"
    },
    {
        id: "16",
        Title: "The Shawshank Redemption",
        Year: "1994",
        Genre: "Drama",
        Director: "Frank Darabont",
        Actors: "Tim Robbins, Morgan Freeman",
        Plot: "A banker is jailed for murder and finds hope",
        Poster: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSf1DK32xKMQzqSl8wnY1BLVu_gdwsRYzVSNM6A03r6c-fEwrif8raKzkFRuerw1KHdDICvOw",
        imdbRating: "9.3"
    },
    {
        id: "17",
        Title: "Forrest Gump",
        Year: "1994",
        Genre: "Drama",
        Director: "Robert Zemeckis",
        Actors: "Tom Hanks, Robin Wright",
        Plot: "A simple man lives through key U.S. events",
        Poster: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTNI2SBzYW95C8Wo7zYV3bzVzem58xPnUzsZGLsnLg17mSMgR574acQZpgNK7a5XeF3THjqgQ",
        imdbRating: "8.8"
    },
    {
        id: "18",
        Title: "The Godfather",
        Year: "1972",
        Genre: "Crime",
        Director: "Francis Ford Coppola",
        Actors: "Marlon Brando, Al Pacino",
        Plot: "The aging patriarch of an organized crime dynasty transfers control to his reluctant son",
        Poster: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQAY2xsJVIZxm3K0gNtOMr9CSCvLdr5kdo3V3pv2HMuUkTBhFzRe5-b8NDRmO1mt5S5Xp_YyQ",
        imdbRating: "9.2"
    },
    {
        id: "19",
        Title: "The Avengers",
        Year: "2012",
        Genre: "Action",
        Director: "Joss Whedon",
        Actors: "Robert Downey Jr., Chris Evans",
        Plot: "Earth's mightiest heroes must come together to stop Loki",
        Poster: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQluFl3GfQDXohBaH-xG3GuRi8T4MDIQPRpCqUGLiE5tXdXbUO0hRFwnshvzg07igEgGg7i",
        imdbRating: "8.0"
    },
    {
        id: "20",
        Title: "Deadpool",
        Year: "2016",
        Genre: "Action",
        Director: "Tim Miller",
        Actors: "Ryan Reynolds, Morena Baccarin",
        Plot: "A mercenary becomes an antihero with dark humor",
        Poster: "https://m.media-amazon.com/images/M/MV5BNzY3ZWU5NGQtOTViNC00ZWVmLTliNjAtNzViNzlkZWQ4YzQ4XkEyXkFqcGc@._V1_.jpg",
        imdbRating: "8.0"
    },

    {
        id: "21",
        Title: "3 Idiots",
        Year: "2009",
        Genre: "Comedy",
        Director: "Rajkumar Hirani",
        Actors: "Aamir Khan, R. Madhavan, Sharman Joshi",
        Plot: "Three engineering students challenge the education system",
        Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRJnCXn6sdK_7DaGdRgFuN32XRNPfk7iiUHQ&s",
        imdbRating: "8.4"
    },
    {
        id: "22",
        Title: "Dangal",
        Year: "2016",
        Genre: "Biography",
        Director: "Nitesh Tiwari",
        Actors: "Aamir Khan, Fatima Sana Shaikh",
        Plot: "A father trains his daughters to become wrestling champions",
        Poster: "https://upload.wikimedia.org/wikipedia/en/9/99/Dangal_Poster.jpg",
        imdbRating: "8.3"
    },
    {
        id: "23",
        Title: "Lagaan",
        Year: "2001",
        Genre: "Drama",
        Director: "Ashutosh Gowariker",
        Actors: "Aamir Khan, Gracy Singh",
        Plot: "Villagers fight British oppression through a cricket match",
        Poster: "https://upload.wikimedia.org/wikipedia/en/thumb/b/b6/Lagaan.jpg/250px-Lagaan.jpg",
        imdbRating: "8.1"
    },
    {
        id: "24",
        Title: "Swades",
        Year: "2004",
        Genre: "Drama",
        Director: "Ashutosh Gowariker",
        Actors: "Shah Rukh Khan, Gayatri Joshi",
        Plot: "An NRI returns to India to bring change to a rural village",
        Poster: "https://upload.wikimedia.org/wikipedia/en/8/85/Swades_poster.jpg",
        imdbRating: "8.2"
    },
    {
        id: "25",
        Title: "Taare Zameen Par",
        Year: "2007",
        Genre: "Drama",
        Director: "Aamir Khan",
        Actors: "Darsheel Safary, Aamir Khan",
        Plot: "A dyslexic child finds his true potential through art",
        Poster: "https://upload.wikimedia.org/wikipedia/en/b/b4/Taare_Zameen_Par_Like_Stars_on_Earth_poster.png",
        imdbRating: "8.4"
    },
    {
        id: "26",
        Title: "PK",
        Year: "2014",
        Genre: "Comedy",
        Director: "Rajkumar Hirani",
        Actors: "Aamir Khan, Anushka Sharma",
        Plot: "An alien questions religious superstitions on Earth",
        Poster: "https://m.media-amazon.com/images/M/MV5BMTYzOTE2NjkxN15BMl5BanBnXkFtZTgwMDgzMTg0MzE@._V1_FMjpg_UX1000_.jpg",
        imdbRating: "8.1"
    },
    {
        id: "27",
        Title: "Chak De! India",
        Year: "2007",
        Genre: "Sports",
        Director: "Shimit Amin",
        Actors: "Shah Rukh Khan",
        Plot: "A coach trains Indian women's hockey team to victory",
        Poster: "https://upload.wikimedia.org/wikipedia/en/0/0c/Chak_De%21_India.jpg",
        imdbRating: "8.2"
    },
    {
        id: "28",
        Title: "Barfi!",
        Year: "2012",
        Genre: "Romance",
        Director: "Anurag Basu",
        Actors: "Ranbir Kapoor, Priyanka Chopra",
        Plot: "A mute boy and autistic girl find love beyond words",
        Poster: "https://m.media-amazon.com/images/M/MV5BMTQzMTEyODY2Ml5BMl5BanBnXkFtZTgwMjA0MDUyMjE@._V1_FMjpg_UX1000_.jpg",
        imdbRating: "8.1"
    },
    {
        id: "29",
        Title: "Zindagi Na Milegi Dobara",
        Year: "2011",
        Genre: "Adventure",
        Director: "Zoya Akhtar",
        Actors: "Hrithik Roshan, Farhan Akhtar",
        Plot: "Three friends rediscover life during a road trip in Spain",
        Poster: "https://upload.wikimedia.org/wikipedia/en/thumb/1/17/Zindagi_Na_Milegi_Dobara.jpg/250px-Zindagi_Na_Milegi_Dobara.jpg",
        imdbRating: "8.2"
    },
    {
        id: "30",
        Title: "Bhaag Milkha Bhaag",
        Year: "2013",
        Genre: "Biography",
        Director: "Rakeysh Omprakash Mehra",
        Actors: "Farhan Akhtar",
        Plot: "Story of Indian athlete Milkha Singh's struggle and glory",
        Poster: "https://upload.wikimedia.org/wikipedia/en/4/42/Bhaag_Milkha_Bhaag_poster.jpg",
        imdbRating: "8.0"
    },
    {
        id: "31",
        Title: "Andhadhun",
        Year: "2018",
        Genre: "Thriller",
        Director: "Sriram Raghavan",
        Actors: "Ayushmann Khurrana, Tabu",
        Plot: "A blind pianist is caught in a web of crime and lies",
        Poster: "https://upload.wikimedia.org/wikipedia/en/4/47/Andhadhun_poster.jpg",
        imdbRating: "8.2"
    },
    {
        id: "32",
        Title: "Queen",
        Year: "2013",
        Genre: "Drama",
        Director: "Vikas Bahl",
        Actors: "Kangana Ranaut",
        Plot: "A woman finds independence after being dumped",
        Poster: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRmlzTRveS4q6StJdB52uwYVTgOpfQ5Xt2NFLiJA9isuAQHRwnW8t_TkZMlVQbID2-VkNAUCw",
        imdbRating: "8.1"
    },
    {
        id: "33",
        Title: "Gully Boy",
        Year: "2019",
        Genre: "Drama",
        Director: "Zoya Akhtar",
        Actors: "Ranveer Singh, Alia Bhatt",
        Plot: "A street rapper rises from the slums of Mumbai",
        Poster: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTpxuHbd0Q2q56g5aVU-kB4GPYcL0b-5xgY6n0XyFhurQ9pusxt5M_8epJwOxrb4n3WGM62",
        imdbRating: "7.9"
    },
    {
        id: "34",
        Title: "Dear Zindagi",
        Year: "2016",
        Genre: "Drama",
        Director: "Gauri Shinde",
        Actors: "Alia Bhatt, Shah Rukh Khan",
        Plot: "A young woman seeks guidance from a free-spirited therapist",
        Poster: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcS4LZSRQsIm_BV1QY-N2vHLn7RbtGegTbAihyI2cdlctpXqbIeXbnYoB-0hlPWP9gUek7W7",
        imdbRating: "7.5"
    },
    {
        id: "35",
        Title: "Padman",
        Year: "2018",
        Genre: "Biography",
        Director: "R. Balki",
        Actors: "Akshay Kumar, Radhika Apte",
        Plot: "A man sets out to make low-cost sanitary pads in India",
        Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSU8eYz4iNMzCvuJC4ThrCU3F1XsCulUEScZGdcf5rb4teQekJH3YjYvlIxpV8t1yzcGRDiiQ",
        imdbRating: "7.9"
    },
    {
        id: "36",
        Title: "Drishyam",
        Year: "2015",
        Genre: "Thriller",
        Director: "Nishikant Kamat",
        Actors: "Ajay Devgn, Tabu",
        Plot: "A man goes to extreme lengths to protect his family",
        Poster: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRE7T7F4y7gL_rzFbpv48CdEitsaxyJmYYeanPA9DYKLa46KJnW_B2BYPtgj0EbdSEdbw4FfQ",
        imdbRating: "8.2"
    },
    {
        id: "37",
        Title: "Munna Bhai M.B.B.S.",
        Year: "2003",
        Genre: "Comedy",
        Director: "Rajkumar Hirani",
        Actors: "Sanjay Dutt, Arshad Warsi",
        Plot: "A goon pretends to be a doctor and transforms lives",
        Poster: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRE7T7F4y7gL_rzFbpv48CdEitsaxyJmYYeanPA9DYKLa46KJnW_B2BYPtgj0EbdSEdbw4FfQ",
        imdbRating: "8.1"
    },
    {
        id: "38",
        Title: "Kahaani",
        Year: "2012",
        Genre: "Thriller",
        Director: "Sujoy Ghosh",
        Actors: "Vidya Balan",
        Plot: "A pregnant woman searches for her missing husband in Kolkata",
        Poster: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTgWAiq0rK460S91aiXcyz6EpCMY9ds-59D0OBUaWnYdAku-Oe1_U-uih5AVSbM__DLCTVx",
        imdbRating: "8.1"
    },
    {
        id: "39",
        Title: "Airlift",
        Year: "2016",
        Genre: "History",
        Director: "Raja Krishna Menon",
        Actors: "Akshay Kumar, Nimrat Kaur",
        Plot: "An Indian businessman helps evacuate Indians from Kuwait",
        Poster: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRAnQmHg8L8pYpEX13EOo3GfC9BggrQa-uNp60pqZjpiPpOU1wRH0zjgwZ5vSXQdp82fdm8Qg",
        imdbRating: "8.0"
    },
    {
        id: "40",
        Title: "Article 15",
        Year: "2019",
        Genre: "Crime",
        Director: "Anubhav Sinha",
        Actors: "Ayushmann Khurrana",
        Plot: "A cop investigates caste-based discrimination in a village",
        Poster: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcR1fwy5R8CBYemq-uRgVCXsNP6gwBtmXgp85H2urJJXD2Qy7TtiEJKhbJlvuKukCtN7XeD-tA",
        imdbRating: "8.1"
    }


]
localStorage.setItem("products", JSON.stringify(product))